-- generated by apps/api/db/seed.mjs — do not edit by hand
-- game_version: 2026.10.1-dev

begin;

insert into catalog_versions (game_version) values ('2026.10.1-dev')
on conflict (game_version) do nothing;

insert into items_catalog (id, type, name, tier, soft_cost, tradeable) values
  ('coral_dagger', 'weapon', 'Coral Blade', 0, 0, true),
  ('wooden_spear', 'weapon', 'Tribal Bone Spear', 0, 200, true),
  ('iron_cutlass', 'weapon', 'Iron Cutlass', 0, 450, true),
  ('ninja_katana', 'weapon', 'Ninja Katana', 1, 800, true),
  ('trident', 'weapon', 'Ocean Trident', 1, 1400, true),
  ('pirate_sabre', 'weapon', 'Pirate Skull Sabre', 1, 2200, true),
  ('laser_saber', 'weapon', 'Plasma Laser Saber', 2, 3800, true),
  ('saw_blade', 'weapon', 'Sawtooth Ripper', 2, 5800, true),
  ('ice_crystal', 'weapon', 'Glacial Ice Spear', 2, 8000, true),
  ('volcano_magma', 'weapon', 'Volcano Magma Blade', 3, 11000, true),
  ('excalibur', 'weapon', 'Holy Excalibur', 3, 15000, true),
  ('thunder_spear', 'weapon', 'Mjolnir Thunder Spear', 3, 19000, true),
  ('chainsaw', 'weapon', 'Hydro Chainsaw', 4, 24000, true),
  ('dragon_horn', 'weapon', 'Dragon Horn Spear', 4, 32000, true),
  ('baby_shark', 'fish', 'Baby Shark', 0, 0, true),
  ('clownfish', 'fish', 'Clownfish (Nemo)', 0, 500, true),
  ('piranha', 'fish', 'Red-Belly Piranha', 0, 1200, true),
  ('pufferfish', 'fish', 'Spiky Puffer', 0, 2500, true),
  ('manta_ray', 'fish', 'Ocean Manta Ray', 0, 4800, true),
  ('anglerfish', 'fish', 'Abyss Anglerfish', 1, 8500, true),
  ('electric_eel', 'fish', 'Volt Electric Eel', 1, 14000, true),
  ('swordfish', 'fish', 'Deep Swordfish', 1, 22000, true),
  ('hammerhead', 'fish', 'Hammerhead Shark', 1, 35000, true),
  ('thresher_shark', 'fish', 'Thresher Shark', 1, 55000, true),
  ('sawshark', 'fish', 'Serrated Sawshark', 2, 80000, true),
  ('tiger_shark', 'fish', 'Tiger Shark', 2, 120000, true),
  ('orca', 'fish', 'Killer Orca', 2, 180000, true),
  ('great_white', 'fish', 'Great White Shark', 2, 260000, true),
  ('narwhal', 'fish', 'Mystic Narwhal', 2, 380000, true),
  ('ghost_shark', 'fish', 'Phantom Ghost Shark', 3, 540000, true),
  ('sea_turtle', 'fish', 'Ancient Sea Turtle', 3, 750000, true),
  ('kraken_squid', 'fish', 'Abyssal Kraken', 3, 1050000, true),
  ('megalodon', 'fish', 'Ancient Megalodon', 3, 1500000, true),
  ('phoenix_fish', 'fish', 'Solar Phoenix Fish', 3, 2100000, true),
  ('sunfish_mola', 'fish', 'Titan Ocean Sunfish', 4, 2900000, true),
  ('cyber_shark', 'fish', 'Cyber Mecha Shark', 4, 4000000, true),
  ('deep_goblin', 'fish', 'Deep-Sea Goblin Shark', 4, 5500000, true),
  ('golden_leviathan', 'fish', 'Golden Leviathan Dragon', 4, 8000000, true),
  ('none', 'hat', 'No Hat', 0, 0, true),
  ('pirate_hat', 'hat', 'Pirate Tricorn', 0, 300, true),
  ('viking_helmet', 'hat', 'Viking Horned Helm', 0, 650, true),
  ('mini_crown', 'hat', 'Royal Mini Crown', 0, 1200, true),
  ('samurai_kabuto', 'hat', 'Samurai Kabuto', 0, 2000, true),
  ('diving_goggles', 'hat', 'Diving Goggles', 0, 3000, true),
  ('top_hat', 'hat', 'Gentleman Top Hat', 0, 4500, true),
  ('cyber_visor', 'hat', 'Neon Cyber Visor', 0, 6500, true),
  ('chef_hat', 'hat', 'Sushi Chef Hat', 0, 9000, true),
  ('angel_halo', 'hat', 'Celestial Angel Halo', 0, 13000, true),
  ('devil_horns', 'hat', 'Abyssal Devil Horns', 0, 18000, true),
  ('party_hat', 'hat', 'Party Cone Hat', 0, 25000, true)
on conflict (id, type) do update set
  name      = excluded.name,
  tier      = excluded.tier,
  soft_cost = excluded.soft_cost;

commit;
