#!/usr/bin/env node
/**
 * Seeds items_catalog + catalog_versions from the real game data
 * (packages/game-core loads apps/web/src/shop.js).
 *
 * Usage:
 *   node apps/api/db/seed.mjs           # writes db/seeds/001_catalog.sql
 *   node apps/api/db/seed.mjs --print   # prints SQL to stdout
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadGame } from '../../../packages/game-core/src/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GAME_VERSION = process.env.GAME_VERSION || '2026.10.1-dev';

const h = loadGame({ seed: 1, scripts: ['shop.js'] });
const cat = h.catalog();

const q = (s) => `'${String(s ?? '').replace(/'/g, "''")}'`;
const n = (v) => (v == null ? 'null' : Number(v));

const tierIndex = (tiers, id) => {
  const i = tiers.findIndex((t) => t.includes(id));
  return i < 0 ? 0 : i;
};

const rows = [];
const push = (id, type, item, tier) => {
  rows.push(
    `  (${q(id)}, ${q(type)}, ${q(item.name || id)}, ${n(tier)}, ${n(item.cost || 0)}, true)`
  );
};

for (const [id, item] of Object.entries(cat.weaponSkins)) push(id, 'weapon', item, tierIndex(cat.weaponTiers, id));
for (const [id, item] of Object.entries(cat.fishSkins)) push(id, 'fish', item, tierIndex(cat.fishTiers, id));
for (const [id, item] of Object.entries(cat.fishHats)) push(id, 'hat', item, 0);

const sql = `-- generated by apps/api/db/seed.mjs — do not edit by hand
-- game_version: ${GAME_VERSION}

begin;

insert into catalog_versions (game_version) values (${q(GAME_VERSION)})
on conflict (game_version) do nothing;

insert into items_catalog (id, type, name, tier, soft_cost, tradeable) values
${rows.join(',\n')}
on conflict (id, type) do update set
  name      = excluded.name,
  tier      = excluded.tier,
  soft_cost = excluded.soft_cost;

commit;
`;

if (process.argv.includes('--print')) {
  process.stdout.write(sql);
} else {
  const outDir = path.join(__dirname, 'seeds');
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, '001_catalog.sql');
  fs.writeFileSync(outFile, sql);
  console.log(`[seed] wrote ${outFile} (${rows.length} items, ${rows.length + 3} statements)`);
}
